version: "3.3"
services:
  golang-demo:
    build: .
#    container_name: golang-demo
#    image: golang-demo:v0.1
    #    env_file:
    #      - ./envfile
    environment:
      - BCF_NACOS_IP=192.168.130.109
    ports:
      - "9195:9195"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 10m
networks:
  default:
    external:
      name: k2data-bcf